### PR TITLE
New api

### PR DESCRIPTION
**Pull request by txdv**
Don't pull yet, I want to make more changes. A review, suggestions and comments are already welcome!

### CODE REVIEW

**Comment by txdv** [comment]
any comments or suggestions?

**Comment by Impyy** [comment]
I'll review it this afternoon and make some changes to it if needed.

**Comment by Impyy** [comment]
Could you squash the commits? I'd like to merge it into new-api and add my changes.
Also, do you still have the code for the tests you showed me some time ago? I think those can come in handy while testing the new api.

**Comment by txdv** [comment]
i can try to remerge this on top of your new commits at the weekened

**Pull request merged**
